---
- name: MongoDB - add pgp key
  apt_key:
    url: https://www.mongodb.org/static/pgp/server-4.0.asc
    state: present

- name: MongoDB - add repository
  apt_repository:
    filename: '/etc/apt/sources.list.d/mongodb.list'
    repo: "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu bionic/mongodb-org/4.0 multiverse"
    state: present

- name: MongoDB - install MongoDB
  apt:
    name: mongodb-org
    state: present
    update_cache: true

- name: MongoDB - enable and run
  systemd:
    name: mongod
    state: started
    enabled: true
...