---
- hosts: all
  become: true
  gather_facts: false
  pre_tasks:
  - name: clone repo
    git:
      repo: https://github.com/express42/reddit.git
      dest: /opt/reddit
      version: microservices_for_mc
  roles:
  #   - post
    - ui
  #   - comment
  #   - db
...
